
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RecoilRootWrapper from "@/wrappers/RecoilRootWrapper";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Leetcode",
  description: "Generated by create next app",
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
    <html lang="en">
      <body className={inter.className}>
      <RecoilRootWrapper>{children}</RecoilRootWrapper>
        </body>
    </html>
   
  );
}
